import type { Metadata, Viewport } from "next";
import "@/assets/styles/globals.scss";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="x-ua-compatible" content="IE=edge, chrome=1"/>
        <meta name="viewport" content='viewport-fit=cover' />
      </head>
      <body
        className={``}
      >
        <Suspense fallback={<p>Loading...</p>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}


export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
